// <auto-generated />
using Desafio_UOL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Desafio_UOL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio_UOL.Models.CodinomeModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GrupoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "codinome");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("T_UOL_CODINOME", (string)null);
                });

            modelBuilder.Entity("Desafio_UOL.Models.GrupoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("T_UOL_GRUPO", (string)null);
                });

            modelBuilder.Entity("Desafio_UOL.Models.JogadorModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CodinomeId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CodinomeId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("T_UOL_JOGADOR", (string)null);
                });

            modelBuilder.Entity("Desafio_UOL.Models.CodinomeModel", b =>
                {
                    b.HasOne("Desafio_UOL.Models.GrupoModel", "Grupo")
                        .WithMany("Codinomes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Desafio_UOL.Models.JogadorModel", b =>
                {
                    b.HasOne("Desafio_UOL.Models.CodinomeModel", "Codinome")
                        .WithOne("Jogador")
                        .HasForeignKey("Desafio_UOL.Models.JogadorModel", "CodinomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codinome");
                });

            modelBuilder.Entity("Desafio_UOL.Models.CodinomeModel", b =>
                {
                    b.Navigation("Jogador")
                        .IsRequired();
                });

            modelBuilder.Entity("Desafio_UOL.Models.GrupoModel", b =>
                {
                    b.Navigation("Codinomes");
                });
#pragma warning restore 612, 618
        }
    }
}
